### ISSUE TITLE
Wbm Component Documentation

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/PLCnextAppExamples#1]
Hey @mnaserddin-pc,
I dont understand what the [WbmComponent app](https://github.com/PLCnext/PLCnextAppExamples/tree/public/DemoApps/DemoPlcnextExtensionsApps/WbmPlcnextComponentApp) does.

How am I supposed to use this?
Can I add my own pages to the WBM?
Like some application specific debug variables or a trend view or something smilar?
Is this part of the repository meant to collect feature requests on WBM functionalities?

kind regards,
Oliver

**Comment by mnaserddin-pc** [comment]
Hello @OWarneke 
The WbmComponent app integrates the PLCnext WBM-Component, which is actually already a part of the PLCnext Firmware. The goal of this demo app is only to show how integrate a PLCnext component independent from its functionality/content

kind regards,
Moataz
